config/routes.rb
Rails.application.routes.draw do
  root to: "owners#index"

  resources :owners do
    resources :machines, only: [:index]
  end

  resources :machines, only: [:show]

  resources :snacks, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord
  validates_presence_of :location

  belongs_to :owner
  has_many :machine_snacks
  has_many :snacks, through: :machine_snacks

  def average_snack_price
    snacks.average(:price)
  end

  def snack_counter
    snacks.count
  end
end

app/models/machine_snack.rb
class MachineSnack < ApplicationRecord
  belongs_to :machine
  belongs_to :snack
end

app/models/owner.rb
class Owner < ApplicationRecord
  validates_presence_of :name

  has_many :machines
end

app/models/snack.rb
class Snack < ApplicationRecord
  validates_presence_of :name, :price

  has_many :machine_snacks
  has_many :machines, through: :machine_snacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  def index
    @owner = Owner.find(params[:owner_id])
  end

  def show
    @machine = Machine.find(params[:id])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all
  end
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController

  def show
    @snack = Snack.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/index.html.erb
<h1><%= @owner.name %> Vending Machines</h1>

<% @owner.machines.each do |machine| %>
  <p><%= link_to machine.location, machine_path(machine)%></p>
<% end %>

app/views/machines/show.html.erb
<h1><%= @machine.location %> Vending Machine</h1>

<h3>Snacks</h3>
<% @machine.snacks.each do |snack| %>
  <%= "#{snack.name} - $#{'%.2f' % snack.price}" %>
<% end %>

Average Price: $<%= @machine.average_price.round(2) %>

app/views/owners/index.html.erb
<h1>Vending Machine Owners</h1>

<ul>
  <% @owners.each do |owner| %>
    <li><%= owner.name %></li>
  <% end %>
</ul>

app/views/snacks/show.html.erb
<h1>Snack Info</h1>

<h3> <%= @snack.name %> </h3
<h3> Price: $<%= @snack.price %> <h3>

  <h3> Locations </h3>
  <ul>
  <% @snack.machines.each do |machine| %>
    <p id="machine_info-<%= machine.id %>">
      <%= machine.location %> has <%= machine.snack_counter %> different kinds of snacks, with an average price of $ <%= machine.average_snack_price  %>
    </p>
  <% end %>
  </ul>